const { addonBuilder, serveHTTP } = require("stremio-addon-sdk");const axios = require("axios");
// ====================== CONFIG ======================const ANILIST_API = "https://graphql.anilist.co";
// Helper: get current seasonfunction getCurrentSeason() {  const month = new Date().getMonth() + 1;  const year = new Date().getFullYear();  if (month >= 1 && month <= 3) return { season: "WINTER", year };  if (month >= 4 && month <= 6) return { season: "SPRING", year };  if (month >= 7 && month <= 9) return { season: "SUMMER", year };  return { season: "FALL", year };}
const builder = new addonBuilder(require("./manifest.json"));
// ====================== CATALOG ======================builder.defineCatalogHandler(async (args) => {  const metas = [];
  // Seasonal catalogs (Fall 2025, etc.)  if (args.id.startsWith("cr-season-")) {    const parts = args.id.replace("cr-season-", "").toUpperCase().split("-");    const season = parts[0];    const year = parseInt(parts[1]);
    const query = `      query ($season: MediaSeason, $year: Int) {        Page(page: 1, perPage: 50) {          media(season: $season, seasonYear: $year, type: ANIME, sort: POPULARITY_DESC) {            id            title { romaji english }            coverImage { extraLarge }            bannerImage            genres          }        }      }    `;
    const res = await axios.post(ANILIST_API, { query, variables: { season, year } });    for (const a of res.data.data.Page.media) {      metas.push({        id: `anilist:${a.id}`,        type: "series",        name: a.title.english || a.title.romaji,        poster: a.coverImage.extraLarge,        background: a.bannerImage || a.coverImage.extraLarge,        genres: a.genres,      });    }  }
  // Simulcast  else if (args.id === "cr-simulcast") {    const { season, year } = getCurrentSeason();    const query = `      query ($season: MediaSeason, $year: Int) {        Page(perPage: 30) {          media(season: $season, seasonYear: $year, isAdult: false, sort: POPULARITY_DESC, type: ANIME) {            id title { english romaji } coverImage { extraLarge }          }        }      }    `;    const res = await axios.post(ANILIST_API, { query, variables: { season, year } });    for (const a of res.data.data.Page.media) {      metas.push({        id: `anilist:${a.id}`,        type: "series",        name: a.title.english || a.title.romaji,        poster: a.coverImage.extraLarge,      });    }  }
  // Popular / Recently Updated (same for simplicity)  else if (["cr-popular", "cr-updated"].ular"].includes(args.id)) {    const query = `query { Page(perPage: 50) { media(sort: POPULARITY_DESC, type: ANIME) { id title { english romaji } coverImage { extraLarge } } } }`;    const res = await axios.post(ANILIST_API, { query });    for (const a of res.data.data.Page.media) {      metas.push({        id: `anilist:${a.id}`,        type: "series",        name: a.title.english || a.title.romaji,        poster: a.coverImage.extraLarge,      });    }  }
  return { metas };});
// ====================== META ======================builder.defineMetaHandler(async (args) => {  const id = args.id.replace(/^anilist:/, "");  const query = `    query ($id: Int) {      Media(id: $id, type: ANIME) {        id        title { english romaji native }        coverImage { large }        bannerImage        description(asHtml: false)        genres        season        seasonYear        duration      }    }  `;  const res = await axios.post(ANILIST_API, { query, variables: { id: parseInt(id) } });  const a = res.data.data.Media;
  return {    meta: {      id: `anilist:${a.id}`,      type: "series",      name: a.title.english || a.title.romaji || a.title.native,      poster: a.coverImage.large,      background: a.bannerImage || a.coverImage.large,      description: a.description?.replace(/<[^>]*>/g, ""),      genres: a.genres,      releaseInfo: `\( {a.season} \){a.seasonYear}`,      runtime: a.duration ? `${a.duration} min` : undefined,    },  };});
// ====================== STREAMS (simple fallback) ======================builder.defineStreamHandler(async (args) => {  // Very simple direct links from a working 2025 source  const id = args.id.replace(/^anilist:/, "");  const ep = args.extra?.episode || 1;
  try {    const info = await axios.get(`https://api.consumet.org/anime/gogoanime/info/${id}`);    const episodeId = info.data.episodes.find(e => e.number === ep)?.id;    if (!episodeId) return { streams: [] };
    const sources = await axios.get(`https://api.consumet.org/anime/gogoanime/watch/${episodeId}`);    const streams = sources.data.sources      .filter(s => s.quality !== "default")      .map(s => ({        url: s.url,        title: `${s.quality}p Direct`,        behaviorHints: { notWebReady: false },      }));
    return { streams };  } catch (e) {    return { streams: [] };  }});
// ====================== START SERVER ======================const port = process.env.PORT || 7000;serveHTTP(builder.getInterface(), { port });
console.log(`Crunchyroll Reborn add-on running on port ${port}`);