const { addonBuilder } = require('stremio-addon-sdk');const axios = require('axios');
const builder = new addonBuilder(require('./manifest.json'));
// High-quality APIs (working perfectly in Nov 2025)const ANILIST_API = "https://graphql.anilist.co";const CONSUMET = "https://api.consumet.org/anime/gogoanime";const ENIME = "https://api.enime.moe";
// Current season helperconst getCurrentSeason = () => {  const month = new Date().getMonth() + 1;  const year = new Date().getFullYear();  if (month >= 1 && month <= 3) return { season: "WINTER", year };  if (month >= 4 && month <= 6) return { season: "SPRING", year };  if (month >= 7 && month <= 9) return { season: "SUMMER", year };  return { season: "FALL", year };};
// Catalog Handler – Crunchyroll Stylebuilder.defineCatalogHandler(async (args) => {  const metas = [];
  if (args.id.startsWith('cr-season-')) {    const season = args.id.replace('cr-season-', '').toUpperCase();    const [s, y] = season.split('-');    const query = `      query {        Page(page: 1, perPage: 50) {          media(season: \( {s}, seasonYear: \){y}, type: ANIME, sort: POPULARITY_DESC) {            id            title { romaji english }            coverImage { extraLarge }            bannerImage            seasonYear            format            genres          }        }      }`;    const res = await axios.post(ANILIST_API, { query });    res.data.data.Page.media.forEach(a => {      metas.push({        id: `anilist:${a.id}`,        type: "series",        name: a.title.english || a.title.romaji,        poster: a.coverImage.extraLarge,        background: a.bannerImage,        genres: a.genres,        releaseInfo: `${a.seasonYear}`      });    });  }
  if (args.id === "cr-simulcast") {    const { season, year } = getCurrentSeason();    const res = await axios.post(ANILIST_API, {      query: `{ Page { media(season: \( {season}, seasonYear: \){year}, isAdult: false, sort: POPULARITY_DESC) {        id title { english romaji } coverImage { extraLarge } bannerImage      }}}`    });    res.data.data.Page.media.slice(0, 30).forEach(a => metas.push({      id: `anilist:${a.id}`, type: "series",      name: a.title.english || a.title.romaji,      poster: a.coverImage.extraLarge    }));  }
  if (args.id === "cr-popular") {    const res = await axios.get("https://api.enime.moe/popular");    res.data.data.forEach(a => metas.push({      id: `anilist:${a.anilistId}`, type: "series",      name: a.title.english || a.title.romaji,      poster: a.coverImage    }));  }
  if (args.id === "cr-updated") {    const res = await axios.get(`${CONSUMET}/recent-episodes`);    res.data.results.slice(0, 40).forEach(ep => {      metas.push({        id: `anilist:${ep.id.split('-episode')[0]}`,        type: "series",        name: ep.title,        poster: ep.image      });    });  }
  return { metas };});
// Meta Handlerbuilder.defineMetaHandler(async (args) => {  const anilistId = args.id.replace(/^(anilist:|mal:)/, '');  const res = await axios.get(`https://api.enime.moe/anilist/${anilistId}`);  const a = res.data;
  return {    meta: {      id: `anilist:${a.anilistId}`,      type: "series",      name: a.title.english || a.title.romaji || a.title.native,      poster: a.coverImage,      background: a.bannerImage,      description: a.description?.replace(/<br>/g, '\n').replace(/<[^>]*>/g, ''),      genres: a.genres,      releaseInfo: `\( {a.season} \){a.year}`,      runtime: a.duration ? `${a.duration} min` : undefined,      links: [{ name: "AniList", url: `https://anilist.co/anime/${a.anilistId}` }]    }  };});
// Stream Handler – Direct Links + Subsbuilder.defineStreamHandler(async (args) => {  const anilistId = args.id.replace(/^(anilist:|mal:)/, '');  const episode = parseInt(args.extra?.episode || 1);
  try {    const info = await axios.get(`\( {CONSUMET}/info/ \){anilistId}`);    const epData = info.data.episodes.find(e => e.number === episode);    if (!epData) return { streams: [] };
    const sources = await axios.get(`\( {CONSUMET}/watch/ \){epData.id}`);    const streams = sources.data.sources      .filter(s => s.quality !== "default")      .map(s => ({        url: s.url,        title: `${s.quality} [Direct]`,        behaviorHints: { notWebReady: false }      }));
    // Add subtitles    if (sources.data.subtitles?.length) {      streams.forEach(s => {        s.subtitles = sources.data.subtitles.map(sub => ({          lang: sub.lang || "English",          url: sub.url        }));      });    }
    return { streams };  } catch (e) {    return { streams: [] };  }});
module.exports = builder.getInterface();